# Generated by Django 6.0 on 2026-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_subscription_user_alter_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='after_payment_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='earn_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='installment_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_principal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='round_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
