# Generated by Django 6.0 on 2026-01-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.CharField(blank=True, help_text='생년월일 (YYYYMMDD)', max_length=8, null=True),
        ),
    ]
