# Generated by Django 6.0 on 2026-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_after_payment_balance_expense_earn_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
